#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/sbin/netlock
CONF=netlock

start_service() {
	local enabled
	enabled=$(uci -q get "$CONF.global.enabled" || echo 0)

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	# Daemon trap handler removes nft table on TERM
	return 0
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
